[build-system]
requires = [
    "setuptools >= 69.5.1",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/fmu/pem/version.py"

[project]
name = "fmu-pem"
description = "pem"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
keywords = ["energy", "subsurface", "seismic", "scientific", "engineering"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: POSIX :: Linux",
    "Natural Language :: English",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
]
dynamic = ["version"]
dependencies = [
    "ert >= 23.0.0",
    "fmu-config",
    "fmu-tools",
    "numpy >= 2.4.6",
    "pydantic",
    "PyYAML >=6.0.3",
    "resfo",
    "rock-physics-open >= 1.0.1",
    "xtgeo >= 4.24.5",
]

[project.optional-dependencies]
tests = [
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "ruff==0.11.7",
    "debugpy",
]
docs = [
    "autoapi",
    "sphinx",
    "sphinx-argparse",
    "sphinx-autodoc-typehints",
    "sphinx-copybutton",
    "sphinx-togglebutton",
    "sphinx_rtd_theme",
]

[project.urls]
Homepage = "https://github.com/equinor/fmu-pem"
Repository = "https://github.com/equinor/fmu-pem"

[project.scripts]
pem = "fmu.pem.__main__:main"
pem_cleanup = "fmu.pem.run_cleanup:run_pem_cleanup"

[project.entry-points.ert]
pem_jobs = "fmu.pem.hook_implementations.jobs"

[tool.mypy]
ignore_missing_imports = true

[tool.ruff]
src = ["src"]
lint.ignore = [
    "C901",
    "F401"
]
lint.select = [
    "C",
    "E",
    "F",
    "I",
    "PIE",
    "Q",
    "RET",
    "RSE",
    "SIM",
    "W",
]
line-length = 88

[tool.ruff.format]
skip-magic-trailing-comma = false
